### ISSUE TITLE
Error  Connecting to irc-ws.chat.twitch.tv on port 443..

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [ponlponl123/-Prototype-AIVTuber#1]
![image](https://user-images.githubusercontent.com/77267159/217098830-ae017e0b-b8cd-4a6e-ab22-60bffdfed3a2.png)

Hello, love the project trying to get me set up and getting this error. 

Possible know what I am doing wrong attempting to make 24-hour twitch and just love to fine-tune things

Thank you for any help

**Comment by ponlponl123** [comment]
This error message indicates that your device is unable to establish a connection to the Twitch IRC WebSocket server on port 443. There could be several reasons for this issue, including network connectivity problems, firewall restrictions, incorrect server address or port number, or the server may be temporarily down.

To resolve this issue, you can try the following steps:

- Check your internet connection and ensure that it is stable and fast.
- Check if your firewall is blocking the connection to the server. If so, temporarily disable the firewall and try again.
- Verify that the server address and port number are correct.
- If the problem persists, try connecting to the server at a later time, as the server may be temporarily down for maintenance or due to technical issues.

**If you still have trouble connecting, it's recommended to reach out to Twitch support for further assistance.**

Thanks for the feedback. I will make it even better in the future! 🙂

**Comment by TheMindExpansionNetwork** [comment]
Thank you for the reply.

I made it a little further but now getting this 
![image](https://user-images.githubusercontent.com/77267159/217133000-39085ffb-c3a3-41c5-aefc-4e2db7217667.png)

Think it was the auth password now just trying to get it connect. 

Please let me know any ideas appreciate the help

**Comment by TheMindExpansionNetwork** [comment]
![image](https://user-images.githubusercontent.com/77267159/217133552-fb3d7a36-8dd9-4963-b2a0-a0a581a4cff1.png)


Yay thinks it is working.

Quick question what's best way to route the audio now 

It looks like it is pushing the samples 

![image](https://user-images.githubusercontent.com/77267159/217133756-294a9579-5a45-497a-80bd-5e2482e295f9.png)


Got vtuber studio setup also this is super exiting
